[2025-08-10T11:19:22.938+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-10T11:19:22.966+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Premier_dag.Alimentation_des_bases_de_données.Mysql_Ingection manual__2025-08-10T11:11:23.376035+00:00 [queued]>
[2025-08-10T11:19:22.975+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Premier_dag.Alimentation_des_bases_de_données.Mysql_Ingection manual__2025-08-10T11:11:23.376035+00:00 [queued]>
[2025-08-10T11:19:22.975+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2025-08-10T11:19:22.987+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): Alimentation_des_bases_de_données.Mysql_Ingection> on 2025-08-10 11:11:23.376035+00:00
[2025-08-10T11:19:22.995+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=213) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-08-10T11:19:22.996+0000] {standard_task_runner.py:63} INFO - Started process 226 to run task
[2025-08-10T11:19:22.996+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Premier_dag', 'Alimentation_des_bases_de_données.Mysql_Ingection', 'manual__2025-08-10T11:11:23.376035+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/PremierDagLake.py', '--cfg-path', '/tmp/tmpvz_murrz']
[2025-08-10T11:19:22.997+0000] {standard_task_runner.py:91} INFO - Job 5: Subtask Alimentation_des_bases_de_données.Mysql_Ingection
[2025-08-10T11:19:23.010+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-08-10T11:19:23.036+0000] {task_command.py:426} INFO - Running <TaskInstance: Premier_dag.Alimentation_des_bases_de_données.Mysql_Ingection manual__2025-08-10T11:11:23.376035+00:00 [running]> on host b798844a50be
[2025-08-10T11:19:23.118+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Premier_dag' AIRFLOW_CTX_TASK_ID='Alimentation_des_bases_de_données.Mysql_Ingection' AIRFLOW_CTX_EXECUTION_DATE='2025-08-10T11:11:23.376035+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-10T11:11:23.376035+00:00'
[2025-08-10T11:19:23.119+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-10T11:19:23.120+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-10T11:19:23.121+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/PremierDagLake.py", line 45, in mysql_Inge
    gestion = Gestion_des_donnees(doc)
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/src/utils_BD.py", line 11, in __init__
    self.postgres_connection = self.get_postCon()
                               ^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/src/utils_BD.py", line 33, in get_postCon
    return create_engine(f"postgresql+psycopg2://{user}:{password}@{host}:{port}/{db}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in create_engine
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/deprecations.py", line 375, in warned
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 514, in create_engine
    u = _url.make_url(url)
        ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/url.py", line 738, in make_url
    return _parse_url(name_or_url)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/url.py", line 794, in _parse_url
    components["port"] = int(components["port"])
                         ^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'None'
[2025-08-10T11:19:23.133+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=Premier_dag, task_id=Alimentation_des_bases_de_données.Mysql_Ingection, execution_date=20250810T111123, start_date=20250810T111922, end_date=20250810T111923
[2025-08-10T11:19:23.144+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 5 for task Alimentation_des_bases_de_données.Mysql_Ingection (invalid literal for int() with base 10: 'None'; 226)
[2025-08-10T11:19:23.182+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-08-10T11:19:23.214+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-10T11:19:23.219+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
